### ISSUE TITLE
Forwarding to SOCKs

### ISSUE THREAD

**Issue by r3a1d3a1** [justmao945/mallory#27]
Hello,

I have a password-protected SSH connection upon which a SOCKs proxy is easily established using the `-D` param.
It'd be great to be able to use _mallory_ or _forward_ to create a HTTP proxy from an **established** SOCKs proxy.
The reason is that I'd like to ensure in case of a MITM attack, the password doesn't get leaked via _mallory_, by relying solely on the builtin `ssh` command for security. (In particular, the warning where it asks whether to add the new machine to the list of known hosts.)

Thank you

**Comment by drewbitt** [comment]
Other libraries like v2ray and "http-proxy-to-socks" do exactly this

**Comment by r3a1d3a1** [comment]
You're right. Tnx.
